#!/bin/bash

export DATA_DIR=/home/hyu/gpu-rodinia/data
#./hotspot.out 1024 4 5000 ${DATA_DIR}/hotspot/temp_1024 ${DATA_DIR}/hotspot/power_1024 output.txt $@
./hotspot.out 512 2 500 ${DATA_DIR}/hotspot/temp_512 ${DATA_DIR}/hotspot/power_512 output.txt $@
