#!/usr/bin/env bash

#There are three datasets:

#./euler3d ../../data/cfd/fvcorr.domn.097K   0
#./euler3d ../../data/cfd/fvcorr.domn.193K   
#./euler3d ../../data/cfd/missile.domn.0.2M  

#replace euler3d with other CFD programs


./euler3d.out ../../data/cfd/missile.domn.0.2M $@
