#!/usr/bin/env bash

#./streamcluster 10 20 16 2048000 204800 1000 none output.txt 1

#for (  i = 1, j=1;  i <= 1;  i++, j=j*2  ))
for i in `seq 1 1`; do
  #echo `expr $j \* 10240` `expr $j \* 1024`
  #./sc_gpu 10 20 16 `expr $j \* 10240` `expr $j \* 1024` 1000 none output.txt 1
  ./streamcluster.out 10 20 256 65536 65536 1000 none output.txt 1 -p 0 -d 0
done
